##############################
#           Imports          #
##############################
import os
import sys
import time
import collections
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from PIL import Image

# Additional imports for ViT model and image preprocessing
import timm
from torchvision import transforms

##############################
#     Global Configurations  #
##############################
# Start overall runtime measurement
global_start_time = time.time()
torch.backends.cudnn.benchmark = True

# File Paths
CSV_FILE = "data/output_list/output_L.csv"       # Input CSV file generated by your QR generator
PRED_DIR = "data/predict"                          # Directory to save prediction CSVs

# Model name (used for saving confusion matrices)
MODEL_NAME = "ViT"

# Create output directories
MODEL_PRED_DIR = os.path.join(PRED_DIR, MODEL_NAME)
os.makedirs(MODEL_PRED_DIR, exist_ok=True)
os.makedirs(os.path.join("cm", MODEL_NAME), exist_ok=True)

##############################
#   Data Preparation         #
##############################
# Load CSV and set the result type to integer
df = pd.read_csv(CSV_FILE)
df['result'] = df['result'].astype(int)
print("Overall label distribution in CSV:", collections.Counter(df['result']))

# Image preprocessing transform for ViT
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
         mean=[0.485, 0.456, 0.406],
         std=[0.229, 0.224, 0.225]
    ),
])

# Custom dataset that loads images based on the paths in the CSV
class QRCodeDataset(Dataset):
    def __init__(self, df, transform):
        self.df = df.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        # Image paths in CSV point to files under "qrcodes"
        image_path = row['QR_Code_Path']
        image = Image.open(image_path).convert("RGB")
        image = self.transform(image)
        label = torch.tensor(row['result'], dtype=torch.long)
        return image, label

##############################
#       Model Definition     #
##############################
# ViT-based classifier model that uses a frozen backbone for feature extraction
class ViTClassifier(nn.Module):
    def __init__(self, vit_model, num_classes=2):
        super(ViTClassifier, self).__init__()
        self.vit_model = vit_model
        # ViT-H/14 feature dimension is 1280
        self.fc = nn.Linear(1280, num_classes)

    def forward(self, images):
        with torch.no_grad():
            features = self.vit_model.forward_features(images)
        cls_token = features[:, 0]  # Use first token as class token
        return self.fc(cls_token)

##############################
#   Training & Evaluation    #
##############################
def train(model, train_loader, val_loader, optimizer, criterion, device, epochs=8):
    """Train the model and evaluate on the validation set each epoch."""
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        avg_loss = total_loss / len(train_loader)
        
        # Validation
        model.eval()
        val_loss = 0
        all_preds, all_labels = [], []
        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)
                val_loss += loss.item()
                preds = torch.argmax(outputs, dim=1).cpu().numpy()
                all_preds.extend(preds)
                all_labels.extend(labels.cpu().numpy())
        avg_val_loss = val_loss / len(val_loader)
        val_precision = precision_score(all_labels, all_preds, zero_division=0)
        val_recall = recall_score(all_labels, all_preds, zero_division=0)
        val_f1 = f1_score(all_labels, all_preds, zero_division=0)
        
        print(f"Epoch {epoch+1}: Train Loss: {avg_loss:.4f}, Val Loss: {avg_val_loss:.4f}, "
              f"Val Precision: {val_precision:.4f}, Val Recall: {val_recall:.4f}, Val F1: {val_f1:.4f}")

def evaluate(model, data_loader, device):
    """Evaluate model on data_loader and return predictions and true labels."""
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for images, labels in data_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds = torch.argmax(outputs, dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.cpu().numpy())
    return all_preds, all_labels

##############################
#        Main Pipeline       #
##############################
# Set device; exit if no GPU is found
device = torch.device("cuda" if torch.cuda.is_available() else sys.exit("Error: No GPU found! Exiting..."))
print(f"Using device: {device}")

# Retrieve sorted unique QR versions
versions = sorted(df['QR_Version'].unique())
print("QR Versions found:", versions)

# Loop over each QR version and train a separate model
for version in versions:
    print(f"\n========== Training for QR Version {version} ==========")
    version_df = df[df['QR_Version'] == version].reset_index(drop=True)
    num_samples = len(version_df)
    print(f"Number of samples for version {version}: {num_samples}")
    
    # Skip if too few samples
    if num_samples < 3000:
        print(f"Not enough samples for version {version}. Skipping training.")
        continue

    # Perform stratified split: 70% train, 10% validation, 20% test
    train_val_df, test_df = train_test_split(version_df, test_size=0.2, random_state=42, stratify=version_df['result'])
    train_df, val_df = train_test_split(train_val_df, test_size=1/8, random_state=42, stratify=train_val_df['result'])
    print(f"Train samples: {len(train_df)}, Validation samples: {len(val_df)}, Test samples: {len(test_df)}")
    
    # Create datasets and data loaders
    train_dataset = QRCodeDataset(train_df, preprocess)
    val_dataset = QRCodeDataset(val_df, preprocess)
    test_dataset = QRCodeDataset(test_df, preprocess)
    
    train_loader = DataLoader(train_dataset, batch_size=1024, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=1024, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=1024, shuffle=False)
    
    # Instantiate a new pre-trained ViT backbone and freeze its weights
    backbone = timm.create_model('vit_huge_patch14_224', pretrained=True)
    backbone.to(device)
    backbone.eval()
    
    # Initialize classifier using the backbone
    model = ViTClassifier(backbone).to(device)
    if torch.cuda.device_count() > 1:
        print(f"Using {torch.cuda.device_count()} GPUs")
        model = nn.DataParallel(model)
    
    # Set up optimizer (only fine-tuning the final FC layer) and loss function
    fc_parameters = model.module.fc.parameters() if isinstance(model, nn.DataParallel) else model.fc.parameters()
    optimizer = optim.AdamW(fc_parameters, lr=0.016)
    criterion = nn.CrossEntropyLoss()
    
    # Train the model on this version's training/validation data
    print(f"--- Training model for version {version} ---")
    train(model, train_loader, val_loader, optimizer, criterion, device)
    
    # Evaluate the model on the test set
    test_preds, test_labels = evaluate(model, test_loader, device)
    precision_v = precision_score(test_labels, test_preds, zero_division=0)
    recall_v = recall_score(test_labels, test_preds, zero_division=0)
    f1_v = f1_score(test_labels, test_preds, zero_division=0)
    # Ensure confusion matrix is 2x2 by specifying labels
    conf_matrix_v = confusion_matrix(test_labels, test_preds, labels=[0, 1])
    
    print(f"\nResults for QR Version {version}:")
    print(f"  Precision: {precision_v:.4f}")
    print(f"  Recall:    {recall_v:.4f}")
    print(f"  F1 Score:  {f1_v:.4f}")
    
    # Save confusion matrix under cm/ViT/
    plt.figure(figsize=(6, 5))
    sns.heatmap(conf_matrix_v, annot=True, fmt='d', cmap='Blues',
                xticklabels=['Benign', 'Malicious'], yticklabels=['Benign', 'Malicious'])
    plt.xlabel('Predicted Label')
    plt.ylabel('True Label')
    plt.title(f'Confusion Matrix - Version {version}')
    cm_filename = f"cm/{MODEL_NAME}/output_L_v{version}_vit_huge.png"
    plt.savefig(cm_filename, dpi=300, bbox_inches="tight")
    plt.close()
    print(f"Confusion matrix saved to: {cm_filename}")
    
    # Save test set predictions in data/predict
    test_df = test_df.copy()
    test_df["predict_label"] = test_preds
    pred_filename = f"{MODEL_PRED_DIR}/vit_huge_output_L_v{version}_predict.csv"
    test_df.to_csv(pred_filename, index=False)
    print(f"Prediction CSV saved as: {pred_filename}")

##############################
#         Final Runtime      #
##############################
global_end_time = time.time()
global_end_time_readable = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(global_end_time))
print(f"\nOverall End time: {global_end_time_readable}")
total_time = global_end_time - global_start_time
hours, remainder = divmod(total_time, 3600)
minutes, seconds = divmod(remainder, 60)
print(f"Overall Total running time: {int(hours):02}:{int(minutes):02}:{int(seconds):02}.{int((seconds % 1) * 100):02}")
